version: '3'
services:
  # nginx-letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   environment:
  #     - NGINX_DOCKER_GEN_CONTAINER=theirstory-nginx-gen-container
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:rw
  #     - nginxconfd:/etc/nginx/conf.d
  #     - vhost:/etc/nginx/vhost.d
  #     - nginxhtml:/usr/share/nginx/html
  #     - certs:/etc/nginx/certs:rw
  #   depends_on:
  #     - nginx

  # node:
  #   environment:
  #     - NODE_ENV=production
  #     - BASE_URL=theirstory.io

  react:
    environment:
      - VIRTUAL_HOST=159.89.47.233
      - NODE_ENV=production
    command: bash -c "npm run build && node server.js"
